### ISSUE TITLE
Digits of precision

### ISSUE THREAD

**Issue by mgayatri77** [haoruigao/Dating-Game#2]
In line 148 of DatingGameServer.java, you have the following: 

if (attribute_weight.scale() > 2) {
    endGame("Dater expressed too much precision on an attribute weight");
    return;          
}

Since we are allowed 4 or fewer digits of precision, shouldn't a scale of 4 be allowed? For example 0.999 has a scale of 3 and less than 4 digits of precision, but is still not allowed by the code.

**Comment by haoruigao** [comment]
Please read the description again:

"The weights may be positive or negative ranging from -1 to 1 and specified as decimal values having at most two digits to the right of the decimal point, e.g. 0.13 but not 0.134."

What you mentioned (4 digit precision) I think is for the score.

Thanks
