### ISSUE TITLE
Modifying attributes

### ISSUE THREAD

**Issue by mgayatri77** [haoruigao/Dating-Game#3]
Are we allowed to modify attributes by 20% of their original values every round or overall? Similarly can we modify a different 5% of attributes at every round or do choose the 5% at the beginning and only modify the same attributes at every round? 

Right now, the server seems to allow attributes to be modified by 20% across all rounds rather than at every round and the 5% of attributes seems to be chosen right at the beginning of the game. Is this the expected behavior?

**Comment by haoruigao** [comment]
Hi,

It should be 20% of their original values every round and 5% of attributes at every round.

You could check [DatingGameServer.java] line 139, the change initialise every turn.

**Comment by mgayatri77** [comment]
In Lines 147-8, you have 
BigDecimal attribute_weight = new BigDecimal(daterInput[attribute_index]);
BigDecimal weight_change = orig_attribute_weight.subtract(attribute_weight);

And then in Lines 158-60 you have 
if(orig_attribute_weight.compareTo(BigDecimal.ZERO) == 0 || weight_change.divide(orig_attribute_weight, RoundingMode.HALF_EVEN).abs().compareTo(maxAlterationPct) > 0)

So suppose your original weight is 0.5
In round 1 you drop by 20%, so it becomes 0.4
In round 2, you drop by another 20% so it becomes 0.3 --> however the "weight_change" is now computed as 0.5-0.3 = 0.2, so the check fails. Is this the expected behaviour?

**Comment by haoruigao** [comment]
Is your warning to be "Dater changed an initial attribute by more than 20%"?
0.3 is based on 0.4, so if you change 0.4 -> 0.3, you modified 25% (0.1/0.4), so it is more than 20%.
Not sure whether I solved your prob

**Comment by mgayatri77** [comment]
Well the original attribute value is 0.5, so we are allowed to change by 0.1 each round right? Or are we allowed to changed by 20% of the attribute value in the previous round?

**Comment by haoruigao** [comment]
Oh, you are allowed to changed by 20% of the attribute value based on the previous round

**Comment by mgayatri77** [comment]
Okay thanks for the clarification! 
I'd suggest changing the readme, because it says this "In each response, P may modify 5% of their attribute weights (P may choose which ones) by **20% each with respect to the original weights**".
